pipeline:
  clone:
    image: plugins/git
    depth: 50
    recursive: true
  publish_branchs:
    image: plugins/docker
#    username: ${DOCKER_USERNAME}
    username: admin
#    password: ${DOCKER_PASSWORD}
    password: bit@ops
    registry: https://hub.ibitcome.com
    #insecure: true
    repo: ${REPO}
    mirror: https://szcj37ae.mirror.aliyuncs.com
    tags:
      - ${DRONE_BRANCH##release/}
    when:
      event: push
      branch: [ release/*, refs/tags/*, master, docker, develop ]
  publish_tags:
    image: plugins/docker
    username: admin
    #username: ${DOCKER_USERNAME}
    password: bit@ops
    #password: ${DOCKER_PASSWORD}
    registry: https://hub.ibitcome.com
    #insecure: true
    repo: ${REPO}
    mirror: https://szcj37ae.mirror.aliyuncs.com
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
      branch: [ release/*, refs/tags/*, master, docker, develop ]
#  notify:
#    image: drillster/drone-email
#    host: smtp.mxhichina.com
#    port: 465
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#    from: devops@rongshutong.com
#    recipients:
#      - dengshijun@rongshutong.com
#    when:
#      branch: [ release/*, refs/tags/*, master, docker, develop ]
#      status: [ failure, success ]
matrix:
  include:
    - REPO: hub.ibitcome.com/backend/pkmserver
